// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item;
namespace UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\productData
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductDataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the UKHO.ADDS.Clients.Kiota.SalesCatalogueService.v1.productData.item collection</summary>
        /// <param name="position">The type of product</param>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.WithProductTypeItemRequestBuilder"/></returns>
        public global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.WithProductTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("productType", position);
                return new global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.WithProductTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.ProductDataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductDataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/productData", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.ProductDataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductDataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/productData", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
