parameters:
- name: DestroyResources
  displayName: "Destroy Environment"
  type: boolean
  default: false

pool: Mare Nectaris

variables:
- group: ESS-Deployment-Variables-DEV
- group: EFS-Dev-Test
- name: AZD_INITIAL_ENVIRONMENT_CONFIG
  value: '{"AZURE_ENV_NAME": "$(AZURE_ENV_NAME)", "AZURE_LOCATION": "$(AZURE_LOCATION)", "AZURE_SUBSCRIPTION_ID": "$(AZURE_SUBSCRIPTION_ID)"}'

stages:
- stage: Deploy
  displayName: Deploy to dev
  dependsOn: []
  jobs:
  - job: AzdDeploy
    displayName: Deploy with azd
    steps:
    - checkout: self
      clean: true

    - script: git submodule update --init --recursive
      displayName: Restore mock submodule
      workingDirectory: '$(Build.SourcesDirectory)'
  
    - script: curl -fsSL https://aka.ms/install-azd.sh | bash
      displayName: Install azd

    - pwsh: azd config set auth.useAzCliAuth "true"
      displayName: Configure azd to use az CLI authentication.

    - task: UseDotNet@2
      inputs:
        version: '9.x'
      displayName: Set up .NET 9

    - task: AzureCLI@2
      displayName: Provision infrastructure
      condition: ne('${{ parameters.DestroyResources }}', true)
      inputs:
        azureSubscription: Exchange-Set-Service-Dev-A-008-02
        scriptType: bash
        scriptLocation: inlineScript
        keepAzSessionActive: true
        inlineScript: |
          azd provision --no-prompt --debug
      env:
        AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        AZURE_ENV_NAME: $(AZURE_ENV_NAME)
        AZURE_LOCATION: $(AZURE_LOCATION)
        AZD_INITIAL_ENVIRONMENT_CONFIG: $(AZD_INITIAL_ENVIRONMENT_CONFIG)
