parameters:
- name: DestroyResources
  displayName: "Destroy Environment"
  type: boolean
  default: false

trigger:
- main

#pool: Mare Nectaris
pool: Mare Nubium

variables:
- group: ESS-Deployment-Variables-DEV
- group: EFS-Dev-Test

stages:
- stage: Deploy
  displayName: Deploy to dev
  dependsOn: []
  jobs:
  - job: AzdDeploy
    displayName: Deploy with azd
    workspace:
      clean: all
    variables:
    - name: AZD_INITIAL_ENVIRONMENT_CONFIG
      value: '{"AZURE_ENV_NAME": "$(AZURE_ENV_NAME)", "AZURE_LOCATION": "$(AZURE_LOCATION)", "AZURE_SUBSCRIPTION_ID": "$(AZURE_SUBSCRIPTION_ID)"}'
    steps:
    - checkout: self
      clean: true

    - script: git submodule update --init --recursive
      displayName: Restore mock submodule
      workingDirectory: '$(Build.SourcesDirectory)'
  
    # - script: |
    #     curl -fsSL https://aka.ms/install-azd.sh | bash
    #     azd version
    #   displayName: Install azd
    # - script: |
    #     powershell -ex AllSigned -c "Invoke-RestMethod 'https://aka.ms/install-azd.ps1' | Invoke-Expression"
    #   displayName: Install azd
    # - task: Bash@3
    #   displayName: Install azd
    #   inputs:
    #     targetType: inline
    #     script: |
    #       curl -fsSL https://aka.ms/install-azd.sh | bash
    - task: setup-azd@1
      displayName: Install azd

    - script: |
        azd version
      displayName: Display azd version

    - pwsh: azd config set auth.useAzCliAuth "true"
      displayName: Configure azd to use az CLI authentication.

    - task: UseDotNet@2
      inputs:
        version: '8.x'
      displayName: Set up .NET 8

    - task: UseDotNet@2
      inputs:
        version: '9.x'
      displayName: Set up .NET 9

    - ${{ if eq(parameters.DestroyResources, true) }}:

      - task: AzureCLI@2
        displayName: Destroy infrastructure
        inputs:
          azureSubscription: Exchange-Set-Service-Dev-A-008-02
          scriptType: bash
          scriptLocation: inlineScript
          keepAzSessionActive: true
          inlineScript: |
            azd down --no-prompt --force --purge --debug
        env:
          AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
          AZURE_ENV_NAME: $(AZURE_ENV_NAME)
          AZURE_LOCATION: $(AZURE_LOCATION)

    - ${{ else }}:

      - task: AzureCLI@2
        displayName: Provision infrastructure
        inputs:
          azureSubscription: Exchange-Set-Service-Dev-A-008-02
          scriptType: bash
          scriptLocation: inlineScript
          keepAzSessionActive: true
          inlineScript: |
            azd provision --no-prompt --debug
        env:
          AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
          AZURE_ENV_NAME: $(AZURE_ENV_NAME)
          AZURE_LOCATION: $(AZURE_LOCATION)
          AZD_INITIAL_ENVIRONMENT_CONFIG: $(AZD_INITIAL_ENVIRONMENT_CONFIG)

      - task: AzureCLI@2
        displayName: Deploy application
        inputs:
          azureSubscription: Exchange-Set-Service-Dev-A-008-02
          scriptType: bash
          scriptLocation: inlineScript
          keepAzSessionActive: true
          inlineScript: |
            azd deploy --no-prompt --debug
        env:
          AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
          AZURE_ENV_NAME: $(AZURE_ENV_NAME)
          AZURE_LOCATION: $(AZURE_LOCATION)
