name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(BuildCounter)

trigger:
  - main

pool: NautilusBuild

variables:
  - name: BuildConfiguration
    value: "Release"
  - name: BuildPlatform
    value: "any cpu"
  - name: BuildCounter
    value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  - name: UkhoAssemblyCompany
    value: "UK Hydrographic Office"
  - name: UkhoAssemblyVersionPrefix
    value: "1.0."
  - name: UkhoAssemblyProduct
    value: "ESS Fulfilment Service"
  - name: UKHOAssemblyCopyright
    value: "Copyright © UK Hydrographic Office"
  - name: SdkVersion
    value: "9.0.x"

stages:
  #- stage: BuildTest
   # displayName: "Build and Test"
    #dependsOn: []
    #jobs:
    #- template: templates/build-test-publish.yml

  - stage: UnitTest
    displayName: "Unit Test & code coverage"
    jobs:
    - job: UnitTestsAndCodeCoverage
      workspace:
        clean: all
      displayName: "Dotnet Test and Publish Code Coverage"
      steps:
        - task: UseDotNet@2
          displayName: Use .NET SDK $(SdkVersion)
          inputs:
            packagetype: sdk
            version: $(SdkVersion)
                     
        - task: DotNetCoreCLI@2
          displayName: ".Net Core - NuGet restore test projects only"
          inputs:
            command: "restore"
            projects: "**/*Tests.csproj"
            feedsToUse: config
            noCache: true
            nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
            workingDirectory: '$(Build.SourcesDirectory)'
            packagesDirectory: '$(Build.SourcesDirectory)\packagesForTests'

        - task: DotNetCoreCLI@2
          displayName: "Dotnet test - EFS Orchestrator Unit Tests"
          inputs:
            command: "test"
            projects: '**/UKHO.ADDS.EFS.Orchestrator.UnitTests.csproj'
            arguments: $(BuildConfiguration) --settings "$(Build.SourcesDirectory)\test.runsettings" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/'
            publishTestResults: true
            testRunTitle: "UnitTests for EFS Orchestrator"

        - task: PowerShell@2
          displayName: "Debug: List TestResults Directory"
          inputs:
            targetType: inline
            script: |
               Write-Host "Listing files in TestResults directory:"
               #Get-ChildItem -Path "$(Build.SourcesDirectory)/" -Recurse
               #Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse
               Write-Host "Listing files in TestResults directory complete."            

        - task: publishcodecoverageresults@2
          displayName: "publish code coverage report for build quality checks"
          inputs:
            summaryfilelocation: '$(Build.SourcesDirectory)/TestResults/coverage.cobertura.xml'             
            failIfCoverageEmpty: true

        - task: PowerShell@2
          displayName: "Generate code coverage report"
          inputs:
            targetType: filePath
            filePath: '$(Build.SourcesDirectory)\CodeCoverageReport.ps1'
            arguments: '-source "$(Build.SourcesDirectory)" -reportFolder "$(Build.ArtifactStagingDirectory)"'

        - task: PublishBuildArtifacts@1
          displayName: "Publish Code coverage"
          inputs:
            PathtoPublish: "$(Build.ArtifactStagingDirectory)/codecoveragereport"
            ArtifactName: codecoveragereport

