// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Catalogue;
using UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products;
namespace UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\productData\{productType}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProductTypeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The catalogue property</summary>
        public global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Catalogue.CatalogueRequestBuilder Catalogue
        {
            get => new global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Catalogue.CatalogueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The products property</summary>
        public global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder Products
        {
            get => new global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.WithProductTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProductTypeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/productData/{productType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.WithProductTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProductTypeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/productData/{productType}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
