api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--blobs
        value: '{{ .Env.STORAGE_BLOBENDPOINT }}'
      - name: connectionstrings--efs-keyvault
        value: '{{ .Env.EFS_KEYVAULT_VAULTURI }}'
      - name: connectionstrings--queues
        value: '{{ .Env.STORAGE_QUEUEENDPOINT }}'
      - name: connectionstrings--tables
        value: '{{ .Env.STORAGE_TABLEENDPOINT }}'
  template:
    containers:
      - image: {{ .Image }}
        name: efs-orchestrator
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: services__adds-mocks-efs__http__0
            value: http://adds-mocks-efs.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__adds-mocks-efs__https__0
            value: https://adds-mocks-efs.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: ConnectionStrings__blobs
            secretRef: connectionstrings--blobs
          - name: ConnectionStrings__efs-keyvault
            secretRef: connectionstrings--efs-keyvault
          - name: ConnectionStrings__queues
            secretRef: connectionstrings--queues
          - name: ConnectionStrings__tables
            secretRef: connectionstrings--tables
    scale:
      minReplicas: 1
tags:
  azd-service-name: efs-orchestrator
  aspire-resource-name: efs-orchestrator
