jobs:
- job: BuildADDSMockService
  workspace:
    clean: all
  displayName: "Dotnet Build ADDS Mock Service"
  steps:

    - checkout: self
      submodules: true

    - task: UseDotNet@2
      displayName: Use .NET SDK $(SdkVersion)
      inputs:
        packageType: sdk
        version: $(SdkVersion)
              
    - task: DotNetCoreCLI@2
      displayName: ".Net Core - NuGet restore for non test projects only"
      inputs:
        command: "restore"
        projects: '**/*ADDSMock.csproj'
        feedsToUse: config
        noCache: true
        nugetConfigPath: '$(Build.SourcesDirectory)\mock\repo\BuildNuget.config'
        workingDirectory: '$(Build.SourcesDirectory)\mock\repo\src\ADDSMock'
        packagesDirectory: '$(Build.SourcesDirectory)\repo\packages'

    - task: DotNetCoreCLI@2
      displayName: "Dotnet build task"
      inputs:
        command: "build"
        projects: '**/*ADDSMock.csproj'
        arguments: '--configuration $(BuildConfiguration)'
