parameters:
# The name of the environment to be used in Azure DevOps.
- name: AzureDevOpsEnvironment
  type: string
# Used to generate job names and, in lower case, to select the correct var/x-deploy.yml variable file.
- name: ShortName
  type: string
# If true, additional debugging will be enabled.
- name: AdditionalDebugging
  type: boolean
  default: false

jobs:
- deployment: ${{ parameters.ShortName }}DeployResources
  displayName: "${{ upper(parameters.ShortName) }} - deploy resources"
  environment: ${{ parameters.AzureDevOpsEnvironment }}
  workspace:
    clean: all
  variables:
  - template: var/${{ lower(parameters.ShortName) }}-deploy.yml
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          clean: true
          submodules: true

        - download: none

        - template: get-retained-resource-details.yml

        - task: AzureCLI@2
          displayName: Deploy permanent infrastructure
          inputs:
            azureSubscription: ${{ variables.AzureSubscription }}
            workingDirectory: $(Build.SourcesDirectory)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              set -e
              az role assignment list --assignee-object-id $(PIPELINE-OBJECT-ID) --role "Storage Blob Data Reader"

              echo "Deploying resources..."
              DEPLOY_SECONDS=$EPOCHSECONDS
              DEPLOYMENT_NAME=$AZURE_ENV_NAME-retain-$DEPLOY_SECONDS
              PIPELINE_DEPLOYMENT_NAME=$AZURE_ENV_NAME-pipeline-roles-$DEPLOY_SECONDS
              cd "$(Build.SourcesDirectory)/infra-retain"

              if [ "${{ parameters.AdditionalDebugging }}" == "True" ]; then
                echo "Current environment variables:"
                echo "--------------------------------------------------------------------------------"
                env | sort
                echo "--------------------------------------------------------------------------------"
                az deployment sub create --name $DEPLOYMENT_NAME --location $AZURE_LOCATION --no-prompt --parameters main.bicepparam --debug
              else
                az deployment sub create --name $DEPLOYMENT_NAME --location $AZURE_LOCATION --no-prompt --parameters main.bicepparam
              fi
          env:
            PIPELINE-OBJECT-ID: $(PIPELINE-OBJECT-ID)
