parameters:
# The name of the environment to be used in Azure DevOps.
- name: AzureDevOpsEnvironment
  type: string
# Used to generate job names and, in lower case, to select the correct var/x-deploy.yml variable file.
- name: ShortName
  type: string
# If true, additional debugging will be enabled.
- name: AdditionalDebugging
  type: boolean
  default: false

jobs:
- deployment: ${{ parameters.ShortName }}DestroyResourceGroup
  displayName: "${{ upper(parameters.ShortName) }} - destroy"
  environment: ${{ parameters.AzureDevOpsEnvironment }}
  workspace:
    clean: all
  variables:
  - template: var/${{ lower(parameters.ShortName) }}-deploy.yml
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          clean: true
          submodules: true

        - download: none
  
        - script: |
            curl -fsSL https://aka.ms/install-azd.sh | bash
            azd version
            azd config set auth.useAzCliAuth "true"
          displayName: Install azd

        - task: AzureCLI@2
          displayName: Destroy infrastructure
          inputs:
            azureSubscription: ${{ variables.AzureSubscription }}
            workingDirectory: $(Build.SourcesDirectory)/src/UKHO.ADDS.EFS.LocalHost
            scriptType: bash
            scriptLocation: inlineScript
            ${{ if eq(parameters.AdditionalDebugging, true) }}:
              inlineScript: |
                set -e
                echo "Current env variables:"
                echo "--------------------------------------------------------------------------------"
                env | sort
                echo "--------------------------------------------------------------------------------"

                azd down --no-prompt --force --purge --debug

                echo "Current azd variables:"
                echo "--------------------------------------------------------------------------------"
                azd env get-values
                echo "--------------------------------------------------------------------------------"
            ${{ else }}:
              inlineScript: |
                azd down --no-prompt --force --purge
          env:
            AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
            AZURE_ENV_NAME: $(AZURE_ENV_NAME)
            AZURE_ADDS_ENVIRONMENT: $(AZURE_ENV_NAME)
            AZURE_LOCATION: $(AZURE_LOCATION)
            AZURE_SUBNET_RESOURCE_ID: $(AZURE_SUBNET_RESOURCE_ID)
