jobs:
- job: UnitTestsAndCodeCoverage
  workspace:
    clean: all
  displayName: Unit tests and code coverage
  steps:
    - checkout: self
      clean: true

    - script: git submodule update --init --recursive
      displayName: Restore mock submodule
      workingDirectory: '$(Build.SourcesDirectory)'

    - task: UseDotNet@2
      displayName: Use .NET SDK $(SdkVersion)
      inputs:
        packageType: sdk
        version: $(SdkVersion)

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.0.x'

    - script: |
        echo "Current directory:"
        pwd
        echo "Matching test projects:"
        dir test\*.csproj /s
        dir configuration\tests\*.csproj /s
      displayName: 'List test projects'

    - task: DotNetCoreCLI@2
      displayName: '.Net Core - NuGet restore test projects only'
      inputs:
        command: 'restore'
        projects: |
          test/UKHO.ADDS.EFS.Orchestrator.UnitTests/UKHO.ADDS.EFS.Orchestrator.UnitTests.csproj,
          test/UKHO.ADDS.EFS.UnitTests/UKHO.ADDS.EFS.UnitTests.csproj,
          test/UKHO.ADDS.EFS.Builder.S100.UnitTests/UKHO.ADDS.EFS.Builder.S100.UnitTests.csproj,
          test/UKHO.ADDS.EFS.Domain.Services.UnitTests/UKHO.ADDS.EFS.Domain.Services.UnitTests.csproj,
          test/UKHO.ADDS.EFS.Domain.UnitTests/UKHO.ADDS.EFS.Domain.UnitTests.csproj,
          test/UKHO.ADDS.EFS.Infrastructure.UnitTests/UKHO.ADDS.EFS.Infrastructure.UnitTests.csproj,
          test/UKHO.ADDS.EFS.Infrastructure.Builders.UnitTests/UKHO.ADDS.EFS.Infrastructure.Builders.UnitTests.csproj,
          configuration/tests/UKHO.ADDS.Aspire.Configuration.Emulator.Tests/UKHO.ADDS.Aspire.Configuration.Emulator.Tests.csproj,
          configuration/tests/UKHO.ADDS.Aspire.Configuration.Seeder.Tests/UKHO.ADDS.Aspire.Configuration.Seeder.Tests.csproj
        feedsToUse: config
        noCache: true
        nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
        workingDirectory: '$(Build.SourcesDirectory)'
        restoreDirectory: '$(Build.SourcesDirectory)\packagesForTests'

    # List of test projects
    - ${{ each testProject in
        [
          'test/UKHO.ADDS.EFS.Orchestrator.UnitTests/UKHO.ADDS.EFS.Orchestrator.UnitTests.csproj',
          'test/UKHO.ADDS.EFS.UnitTests/UKHO.ADDS.EFS.UnitTests.csproj',
          'test/UKHO.ADDS.EFS.Builder.S100.UnitTests/UKHO.ADDS.EFS.Builder.S100.UnitTests.csproj',
          'test/UKHO.ADDS.EFS.Domain.Services.UnitTests/UKHO.ADDS.EFS.Domain.Services.UnitTests.csproj',
          'test/UKHO.ADDS.EFS.Domain.UnitTests/UKHO.ADDS.EFS.Domain.UnitTests.csproj',
          'test/UKHO.ADDS.EFS.Infrastructure.UnitTests/UKHO.ADDS.EFS.Infrastructure.UnitTests.csproj',
          'test/UKHO.ADDS.EFS.Infrastructure.Builders.UnitTests/UKHO.ADDS.EFS.Infrastructure.Builders.UnitTests.csproj',
          'configuration/tests/UKHO.ADDS.Aspire.Configuration.Emulator.Tests/UKHO.ADDS.Aspire.Configuration.Emulator.Tests.csproj',
          'configuration/tests/UKHO.ADDS.Aspire.Configuration.Seeder.Tests/UKHO.ADDS.Aspire.Configuration.Seeder.Tests.csproj'
        ]
      }}:
      - task: DotNetCoreCLI@2
        displayName: 'Dotnet test - Perform unit tests for ${{ testProject }}'
        inputs:
          command: 'test'
          projects: '${{ testProject }}'
          arguments: '--configuration $(BuildConfiguration) --settings "$(Build.SourcesDirectory)\test.runsettings" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/test/$(BuildConfiguration)/$(basename ${{ testProject }} .csproj).coverage.cobertura.xml --no-restore'
          publishTestResults: true
          testRunTitle: UnitTests
          restoreDirectory: '$(Build.SourcesDirectory)\packagesForTests'

    - script: |
        echo "Listing coverage files:"
        dir $(Build.SourcesDirectory)\test\*.coverage.cobertura.xml /s
      displayName: 'List coverage files'

    - task: PowerShell@2
      displayName: "Generate code coverage report"
      inputs:
        targetType: filePath
        filePath: '$(Build.SourcesDirectory)\.azdo\pipelines\powershell\CodeCoverageReport.ps1'
        arguments: '-reports "$(Build.SourcesDirectory)/test/**/*.coverage.cobertura.xml" -targetdir "$(Build.ArtifactStagingDirectory)/codecoveragereport" -reporttypes HtmlInline_AzurePipelines;Cobertura'

    - task: PublishBuildArtifacts@1
      displayName: "Publish Code coverage"
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)/codecoveragereport"
        ArtifactName: codecoveragereport"
