using './adds-configuration.module.bicep'

param adds_configuration_containerimage = readEnvironmentVariable('CONTAINER_IMAGE')
param adds_configuration_containerport = readEnvironmentVariable('CONTAINER_PORT')
param adds_configuration_identity_outputs_clientid = readEnvironmentVariable('ADDS_CONFIGURATION_IDENTITY_CLIENTID')
param adds_configuration_identity_outputs_id = readEnvironmentVariable('ADDS_CONFIGURATION_IDENTITY_ID')
param adds_configuration_kv_outputs_vaulturi = readEnvironmentVariable('ADDS_CON_KV_VAULTURI')
param adds_configuration_was_outputs_tableendpoint = readEnvironmentVariable('ADDS_CON_WAS_TABLEENDPOINT')
param efs_cae_outputs_azure_container_apps_environment_default_domain = readEnvironmentVariable('EFS_CAE_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN')
param efs_cae_outputs_azure_container_apps_environment_id = readEnvironmentVariable('EFS_CAE_AZURE_CONTAINER_APPS_ENVIRONMENT_ID')
param efs_cae_outputs_azure_container_registry_endpoint = readEnvironmentVariable('EFS_CAE_AZURE_CONTAINER_REGISTRY_ENDPOINT')
param efs_cae_outputs_azure_container_registry_managed_identity_id = readEnvironmentVariable('EFS_CAE_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID')
