# Use the .NET 9 SDK image for build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

# Optional build configuration argument (default to Release)
ARG BUILD_CONFIGURATION=Release

# Create work directories
WORKDIR /app

# Copy csproj files first to leverage layer caching
COPY ["UKHO.ADDS.EFS.Builder.S63/UKHO.ADDS.EFS.Builder.S63.csproj", "UKHO.ADDS.EFS.Builder.S63/"]
COPY ["UKHO.ADDS.EFS.Builder.Common/UKHO.ADDS.EFS.Builder.Common.csproj", "UKHO.ADDS.EFS.Builder.Common/"]
COPY ["UKHO.ADDS.EFS.Domain/UKHO.ADDS.EFS.Domain.csproj", "UKHO.ADDS.EFS.Domain/"]


RUN dotnet restore "UKHO.ADDS.EFS.Builder.S63/UKHO.ADDS.EFS.Builder.S63.csproj"

# Copy remaining files and publish
COPY . .

RUN dotnet publish UKHO.ADDS.EFS.Builder.S63/UKHO.ADDS.EFS.Builder.S63.csproj -c $BUILD_CONFIGURATION -o /app/pub

# Final Layer runtime only
FROM mcr.microsoft.com/dotnet/aspnet:9.0

WORKDIR /app
COPY --from=build /app/pub .

# Define default entrypoint
ENTRYPOINT ["dotnet", "UKHO.ADDS.EFS.Builder.S63.dll"]
