// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models;
using UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductIdentifiers;
using UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductVersions;
namespace UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\productData\{productType}\products
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The productIdentifiers property</summary>
        public global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductIdentifiers.ProductIdentifiersRequestBuilder ProductIdentifiers
        {
            get => new global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductIdentifiers.ProductIdentifiersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The productVersions property</summary>
        public global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductVersions.ProductVersionsRequestBuilder ProductVersions
        {
            get => new global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductVersions.ProductVersionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/productData/{productType}/products?sinceDateTime={sinceDateTime}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/productData/{productType}/products?sinceDateTime={sinceDateTime}", rawUrl)
        {
        }
        /// <summary>
        /// Get all releasable changes to products since a date
        /// </summary>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ErrorDescription">When receiving a 400 status code</exception>
        /// <exception cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.DefaultErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.DefaultErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductResponse?> GetAsync(Action<RequestConfiguration<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductResponse> GetAsync(Action<RequestConfiguration<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ErrorDescription.CreateFromDiscriminatorValue },
                { "404", global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.DefaultErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.DefaultErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductResponse>(requestInfo, global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get all releasable changes to products since a date
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get all releasable changes to products since a date
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsRequestBuilderGetQueryParameters 
        {
            /// <summary>The date and time from which changes are requested. Any changes since the date will be returned.</summary>
            [QueryParameter("sinceDateTime")]
            public DateTimeOffset? SinceDateTime { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V1.ProductData.Item.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
