// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models;
namespace UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100.Basic
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\catalogues\s100\basic
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BasicRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100.Basic.BasicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BasicRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/catalogues/s100/basic", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100.Basic.BasicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BasicRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/catalogues/s100/basic", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve the latest S-100 basic catalogue data, including product names, editions, updates, and statuses
        /// </summary>
        /// <returns>A List&lt;global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100BasicCatalogue&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ErrorDescription">When receiving a 400 status code</exception>
        /// <exception cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.DefaultErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.UnsupportedMediaTypeError">When receiving a 415 status code</exception>
        /// <exception cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.DefaultErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100BasicCatalogue>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100BasicCatalogue>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ErrorDescription.CreateFromDiscriminatorValue },
                { "404", global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.DefaultErrorResponse.CreateFromDiscriminatorValue },
                { "415", global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.UnsupportedMediaTypeError.CreateFromDiscriminatorValue },
                { "500", global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.DefaultErrorResponse.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100BasicCatalogue>(requestInfo, global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100BasicCatalogue.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Retrieve the latest S-100 basic catalogue data, including product names, editions, updates, and statuses
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100.Basic.BasicRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100.Basic.BasicRequestBuilder WithUrl(string rawUrl)
        {
            return new global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100.Basic.BasicRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BasicRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
