// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models;
namespace UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Products.S100.ProductVersions
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\products\s100\productVersions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductVersionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Products.S100.ProductVersions.ProductVersionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductVersionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/products/s100/productVersions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Products.S100.ProductVersions.ProductVersionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductVersionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/products/s100/productVersions", rawUrl)
        {
        }
        /// <summary>
        /// Get the latest baseline, releasable versions for requested products since a specified version
        /// </summary>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100ProductResponse"/></returns>
        /// <param name="body">An array of S-100 product version objects, each representing a unique product name, edition number, and update number for the S-100 standard.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ErrorDescription">When receiving a 400 status code</exception>
        /// <exception cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.UnsupportedMediaTypeError">When receiving a 415 status code</exception>
        /// <exception cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.DefaultErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100ProductResponse?> PostAsync(List<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100ProductVersions> body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100ProductResponse> PostAsync(List<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100ProductVersions> body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ErrorDescription.CreateFromDiscriminatorValue },
                { "415", global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.UnsupportedMediaTypeError.CreateFromDiscriminatorValue },
                { "500", global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.DefaultErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100ProductResponse>(requestInfo, global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100ProductResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the latest baseline, releasable versions for requested products since a specified version
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">An array of S-100 product version objects, each representing a unique product name, edition number, and update number for the S-100 standard.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(List<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100ProductVersions> body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(List<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.S100ProductVersions> body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Products.S100.ProductVersions.ProductVersionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Products.S100.ProductVersions.ProductVersionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Products.S100.ProductVersions.ProductVersionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductVersionsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
