// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProductResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The productCounts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductCounts? ProductCounts { get; set; }
#nullable restore
#else
        public global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductCounts ProductCounts { get; set; }
#endif
        /// <summary>The products property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.Products>? Products { get; set; }
#nullable restore
#else
        public List<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.Products> Products { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductResponse"/> and sets the default values.
        /// </summary>
        public ProductResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "productCounts", n => { ProductCounts = n.GetObjectValue<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductCounts>(global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductCounts.CreateFromDiscriminatorValue); } },
                { "products", n => { Products = n.GetCollectionOfObjectValues<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.Products>(global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.Products.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.ProductCounts>("productCounts", ProductCounts);
            writer.WriteCollectionOfObjectValues<global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models.Products>("products", Products);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
