// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProductCounts_requestedProductsNotReturned_reason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "productWithdrawn")]
        #pragma warning disable CS1591
        ProductWithdrawn,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalidProduct")]
        #pragma warning disable CS1591
        InvalidProduct,
        #pragma warning restore CS1591
        [EnumMember(Value = "noDataAvailableForCancelledProduct")]
        #pragma warning disable CS1591
        NoDataAvailableForCancelledProduct,
        #pragma warning restore CS1591
        [EnumMember(Value = "duplicateProduct")]
        #pragma warning disable CS1591
        DuplicateProduct,
        #pragma warning restore CS1591
    }
}
