// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace UKHO.ADDS.Clients.Kiota.SalesCatalogueService.Models
{
    /// <summary>Current status of the product. Can be one of `newEdition`, `update`, or `cancellation`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum S100BasicCatalogue_status_statusName
    {
        [EnumMember(Value = "newEdition")]
        #pragma warning disable CS1591
        NewEdition,
        #pragma warning restore CS1591
        [EnumMember(Value = "update")]
        #pragma warning disable CS1591
        Update,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancellation")]
        #pragma warning disable CS1591
        Cancellation,
        #pragma warning restore CS1591
        [EnumMember(Value = "newDataset")]
        #pragma warning disable CS1591
        NewDataset,
        #pragma warning restore CS1591
    }
}
