// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100.Basic;
namespace UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\catalogues\s100
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class S100RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The basic property</summary>
        public global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100.Basic.BasicRequestBuilder Basic
        {
            get => new global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100.Basic.BasicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100.S100RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public S100RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/catalogues/s100", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.SalesCatalogueService.V2.Catalogues.S100.S100RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public S100RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/catalogues/s100", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
