using './main.bicep'

param resourceGroupName = readEnvironmentVariable('EFS_RETAIN_RESOURCE_GROUP')
param appResourceGroupName = readEnvironmentVariable('EFS_RESOURCE_GROUP')
param efsServiceIdentityPartialName = readEnvironmentVariable('EFS_SERVICE_IDENTITY_PARTIAL_NAME')
param efsLogAnalyticsWorkspacePartialName = readEnvironmentVariable('EFS_LOG_ANALYTICS_WORKSPACE_PARTIAL_NAME')
param efsApplicationInsightsPartialName = readEnvironmentVariable('EFS_APPLICATION_INSIGHTS_PARTIAL_NAME')
param efsAppConfigurationPartialName = readEnvironmentVariable('EFS_APP_CONFIGURATION_PARTIAL_NAME')
param efsEventHubsNamespacePartialName = readEnvironmentVariable('EFS_EVENT_HUBS_NAMESPACE_PARTIAL_NAME')
param efsContainerRegistryPartialName = readEnvironmentVariable('EFS_CONTAINER_REGISTRY_PARTIAL_NAME')
param efsContainerAppsEnvironmentPartialName = readEnvironmentVariable('EFS_CONTAINER_APPS_ENVIRONMENT_PARTIAL_NAME')
param efsStorageAccountPartialName = readEnvironmentVariable('EFS_STORAGE_ACCOUNT_PARTIAL_NAME')
param location = readEnvironmentVariable('AZURE_LOCATION')
param pipelineDeploymentName = readEnvironmentVariable('PIPELINE_DEPLOYMENT_NAME')
param pipelineClientObjectId = readEnvironmentVariable('PIPELINE-CLIENT-OBJECT-ID')
param subnetResourceId = readEnvironmentVariable('AZURE_SUBNET_RESOURCE_ID')
param zoneRedundant = bool(readEnvironmentVariable('AZURE_ZONE_REDUNDANT'))
