# Use the official Tomcat image as a base
FROM tomcat:9.0
 
# Copy the WAR file to the webapps directory of Tomcat
# COPY /src/xchg-2.4.war /usr/local/tomcat/webapps/
COPY xchg-2.4.war /usr/local/tomcat/webapps/ 
# Expose the default port
EXPOSE 8080
 
# Optional: Set environment variables
# ENV some_variable=some_value
